package main

import (
	"log"

	"github.com/marianina8/audiofile/cmd"
	"github.com/spf13/cobra/doc"
)

func main() {
	header := &doc.GenManHeader{
		Title:  "Audiofile",
		Source: "Auto generated by marianina8",
	}
	err := doc.GenManTree(cmd.RootCMD(), header, "./pages")
	if err != nil {
		log.Fatal(err)
	}
}
