version: '3'
services:
  cli:
    build:
        context: .
        dockerfile: cli.Dockerfile
    image: audiofile:cli
    network_mode: host
    depends_on:
      - api
  api:
    build:
        context: .
        dockerfile: api.Dockerfile
    image: audiofile:api
    ports:
      - "8000:8000"